CREATE TABLE `busi_model` (
  `I_RECORDID` bigint(64) NOT NULL AUTO_INCREMENT COMMENT '记录编号',
  `C_ATTRIBUTE` varchar(20) NOT NULL COMMENT '字段名称',
  `C_DESCRIB` varchar(50) NOT NULL COMMENT '字段中文名称',
  `C_DATATYPE` varchar(10) NOT NULL COMMENT '字段数据类型',
  `C_CONTROLSTYPE` varchar(30) NOT NULL COMMENT '字段控件类型',
  `C_CONTROLSCONTENT` varchar(200) NOT NULL COMMENT '字段控件内容',
  `C_FIELDTYPE` varchar(2) NOT NULL DEFAULT '01' COMMENT '字段类型',
  PRIMARY KEY (`I_RECORDID`),
  UNIQUE KEY `busi_model_idx1` (`C_ATTRIBUTE`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8;

CREATE TABLE `busi_model_attr` (
  `I_RECORDID` bigint(64) NOT NULL AUTO_INCREMENT COMMENT '记录编号',
  `C_ATTRIBUTE` varchar(20) NOT NULL COMMENT '字段名称',
  `C_MODELID` varchar(20) NOT NULL COMMENT '模型编号',
  PRIMARY KEY (`I_RECORDID`),
  UNIQUE KEY `C_ATTRIBUTE` (`C_ATTRIBUTE`,`C_MODELID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=38 DEFAULT CHARSET=utf8;

CREATE TABLE `busi_model_rule` (
  `I_RECORDID` bigint(64) NOT NULL AUTO_INCREMENT COMMENT '记录编号',
  `C_MODELID` varchar(20) NOT NULL COMMENT '模型编号',
  `C_RULECONTENT` varchar(1024) DEFAULT NULL COMMENT '模型属性字段',
  PRIMARY KEY (`I_RECORDID`),
  UNIQUE KEY `C_MODELID` (`C_MODELID`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8;

CREATE TABLE `busi_model_ruleitem` (
  `I_RECORDID` bigint(64) NOT NULL AUTO_INCREMENT COMMENT '记录编号',
  `C_MODELID` varchar(20) NOT NULL COMMENT '模型编号',
  `C_RULEID` varchar(20) NOT NULL COMMENT '规则编号',
  `C_CONDITIONID` varchar(20) NOT NULL COMMENT '条件编号',
  `C_CONDITIONTYPE` varchar(20) NOT NULL DEFAULT 'when' COMMENT '条件标识',
  `C_RELATION` varchar(10) DEFAULT NULL COMMENT '条件之间关系',
  `C_ATTRIBUTE` varchar(50) NOT NULL COMMENT '模型属性字段',
  `C_EXPRESSION` varchar(10) NOT NULL COMMENT '条件表达式',
  `C_VALUES` varchar(10) NOT NULL COMMENT '条件判断值',
  PRIMARY KEY (`I_RECORDID`)
) ENGINE=InnoDB AUTO_INCREMENT=196 DEFAULT CHARSET=utf8;

CREATE TABLE `busi_model_ruleweighted` (
  `I_RECORDID` bigint(64) NOT NULL AUTO_INCREMENT COMMENT '记录编号',
  `C_MODELID` varchar(20) NOT NULL COMMENT '模型编号',
  `C_RULEID` varchar(20) NOT NULL COMMENT '规则编号',
  `C_CONDITIONID` varchar(20) NOT NULL COMMENT '条件编号',
  `C_CONDITIONTYPE` varchar(20) NOT NULL DEFAULT 'when' COMMENT '条件标识',
  `C_RELATION` varchar(10) DEFAULT NULL COMMENT '条件之间关系',
  `C_ATTRIBUTE` varchar(50) NOT NULL COMMENT '模型属性字段',
  `C_EXPRESSION` varchar(10) DEFAULT NULL COMMENT '条件表达式',
  `C_VALUES` varchar(10) NOT NULL COMMENT '条件判断值',
  PRIMARY KEY (`I_RECORDID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;